### PR TITLE
fix image builds with update of dependencies

### PR DESCRIPTION
**Pull request by olitha**
Docker images fail to build in pipeline because linux image packages was updated in debian repo.

I updated to 4.19.0-14

### CODE REVIEW

**Comment by olitha** [comment]
fixed linux and freebsd but could someone have a look into the solaris image build?

**Comment by olitha** [comment]
Anything new here?

**Comment by reitermarkus** [comment]
Might be best to disable the Solaris images and let someone who needs them fix them.

**Comment by olitha** [comment]
commented out solaris images

**Review by reitermarkus — APPROVED** [review]

**Comment by olitha** [comment]
build fails because of probably temporary 502 in crates.io :( Some way to start it again?

**Comment by reitermarkus** [comment]
bors retry

**Pull request merged**
