### PR TITLE
 Add support for clippy.

### PR DESCRIPTION
**Pull request by reitermarkus**
Automatically install `clippy` for the appropriate toolchain. Also fixes `rust-src` not being installed for the appropriate toolchain on macOS.

### CODE REVIEW

**Comment by reitermarkus** [comment]
The test failures look unrelated.

**Comment by Dylan-DPC** [comment]
bors: try

**Comment by reitermarkus** [comment]
This is also blocked on https://github.com/rust-lang/rust/issues/57426.

**Comment by reitermarkus** [comment]
This should be working now with the new nightly.

**Comment by Dylan-DPC** [comment]
hopefully

bors: try

**Comment by Dylan-DPC** [comment]
bors: r+

**Pull request merged**
