### PR TITLE
Fix toolchain path on macOS.

### PR DESCRIPTION
**Pull request by reitermarkus**
This automatically installs the Linux toolchain on macOS, so it can be used by the Docker images, and then installs the targets for the Linux toolchain instead of the default one.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
bors: try

**Comment by Dylan-DPC** [comment]
oops, sorry for tthe delay

bors: r+

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by reitermarkus** [comment]
Would be great to have a new release so that “zero setup” is also true for macOS.

**Pull request merged**
