### PR TITLE
Fix CI config.

### PR DESCRIPTION
**Pull request by reitermarkus**
Fixes various things which are currently failing.

### CODE REVIEW

**Comment by jamesmunns** [comment]
bors try

**Comment by reitermarkus** [comment]
The failures show `libssl1.0.2` not being found, despite explicitly being set to use `libssl1.1`. Maybe clear the Travis cache? It worked fine on my fork, as you can see: https://travis-ci.com/reitermarkus/cross/builds/113788760

**Comment by reitermarkus** [comment]
Is anything blocking this from being merged?

**Comment by jamesmunns** [comment]
@reitermarkus nope, thanks for the reping!

**Comment by reitermarkus** [comment]
Seems to be a spurious network failure.

**Comment by jamesmunns** [comment]
bors retry

**Comment by reitermarkus** [comment]
Network failure again.

**Comment by jamesmunns** [comment]
bors retry

**Pull request merged**
