### PR TITLE
Bump version to 0.2.1.

### PR DESCRIPTION
**Pull request by reitermarkus**
Prepare 0.2.1 release.

Updated some dependencies and disabled the `powerpc64-unknown-linux-gnu` and `sparc64-unknown-linux-gnu` images since they keep breaking.

### CODE REVIEW

**Comment by reitermarkus** [comment]
bors try

**Comment by reitermarkus** [comment]
bors try

**Comment by reitermarkus** [comment]
bors r=adamgreig

**Comment by reitermarkus** [comment]
bors r=adamgreig

**Comment by nagisa** [comment]
Is there any description of how the sparc/ppc images keep breaking?

**Pull request merged**
