### PR TITLE
freebsd: Add libprocstat.so

### PR DESCRIPTION
**Pull request by svenstaro**
If we don't add this library, we'll eventually run into linking problems due to libprocstat.so not being found.

### CODE REVIEW

**Comment by svenstaro** [comment]
I have no idea why this fails to build.

**Comment by Emilgardis** [comment]
Its unrelated, probably https://github.com/nix-rust/nix/issues/1491

Need to bump nix version

**Comment by Emilgardis** [comment]
bors try

**Comment by svenstaro** [comment]
So bors says it works but the CI still fails?

**Comment by Emilgardis** [comment]
We merged a fix for the CI in #583, but github actions doesn't run on the (would be) merge commit, it runs on the prs ref.
If you want to fix it, you could rebase your branch, but there is no need, as bors runs on the merged ref.

I don't really feel comfortable merging this as I'm not familiar with FreeBSD. But it doesn't seem like it'd be bad to have.

**Comment by Emilgardis** [comment]
@reitermarkus r=me if you think this is ok, i suspect it is

**Comment by svenstaro** [comment]
Rebased and added CHANGELOG entry.

> I don't really feel comfortable merging this as I'm not familiar with FreeBSD. But it doesn't seem like it'd be bad to have.

Since this really just adds a library I think the possible bad impact is fairly limited. Without this, my fairly boring Rust program didn't compile and with it, it does. :)

**Review by Emilgardis — APPROVED** [review]
Thanks!

**Comment by svenstaro** [comment]
Thank _you_ for taking care of cross. I think cross fills an important role in the Rust ecosystem and it needs love. :)

**Comment by svenstaro** [comment]
Any chance for a good ol' mergerino?

**Comment by Emilgardis** [comment]
ill merge it, don't see that should be an issue.

Thank you!

bors r+

**Comment by svenstaro** [comment]
Huh how did this fail?

**Comment by Emilgardis** [comment]
https://dev.azure.com/rust-embedded/cross/_build/results?buildId=930&view=logs&j=6e847cca-24ce-5b2d-e476-7fadc4226834&t=4f4f83a6-27d6-5138-5def-6e63a5c30d1a&l=16603

404, could be temporary or it needs to be changed

**Comment by svenstaro** [comment]
It needs to be updated to https://pkg.freebsd.org/FreeBSD:12:i386/quarterly/All/openssl-1.1.1l,1.txz. I'm submitting another PR I guess.

**Comment by svenstaro** [comment]
Alright @Emilgardis I posted a fix as #588.

**Pull request merged**
