### PR TITLE
aarch64-unknown-linux-musl: do not set RUSTFLAGS

### PR DESCRIPTION
**Pull request by jonas-schievink**
https://github.com/rust-lang/rust/issues/46651 has been fixed, and this helps with https://github.com/rust-embedded/cross/issues/463

### CODE REVIEW

**Review by Dylan-DPC — DISMISSED** [review]

**Comment by jonas-schievink** [comment]
Hmm, seems like we need to wait for the next Rust release (or 2) until this can be removed

**Review by reitermarkus — APPROVED** [review]

**Comment by reitermarkus** [comment]
bors retry

**Comment by jonas-schievink** [comment]
@reitermarkus this doesn't look spurious to me

**Comment by reitermarkus** [comment]
You're right.

**Comment by reitermarkus** [comment]
bors cancel

**Comment by jonas-schievink** [comment]
Cool, everything except asmjs-unknown-emscripten seems to be working with beta Rust. The remaining issue is caused by https://github.com/rust-lang/rust/issues/76679.

**Comment by japaric** [comment]
PR #497 is an alternative to this PR that should also work with old toolchains (1.42)

**Comment by jonas-schievink** [comment]
https://github.com/rust-embedded/cross/pull/497 has landed, so closing this!

**Pull request closed without merging**
