### PR TITLE
Upgrade OpenSSL to 1.0.2p

### PR DESCRIPTION
**Pull request by bgermann**

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by Bobo1239** [comment]
Spurious failure:
```
++ curl ftp://ftp.netbsd.org/pub/pkgsrc/pkgsrc-2017Q1/pkgsrc/lang/gcc5/patches/patch-libstdc++-v3_config_os_bsd_netbsd_ctype__base.h
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (9) Server denied you to change to the given directory
```

**Comment by jamesmunns** [comment]
bors retry

**Comment by jamesmunns** [comment]
Looks like the same failure. Is the source down/still valid?

**Comment by Dylan-DPC** [comment]
bors: try

**Pull request merged**
