### PR TITLE
Refactor Dockerfiles.

### PR DESCRIPTION
**Pull request by reitermarkus**
Simplify Dockerfile directory structure.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Any opinion on this?

**Comment by reitermarkus** [comment]
bors try

**Comment by reitermarkus** [comment]
bors try

**Comment by reitermarkus** [comment]
bors try

**Comment by Dylan-DPC** [comment]
@reitermarkus you might want to exclude the dragonfly build or allow it to fail in the CI since the CI is failing unrelated to this PR

**Comment by Dylan-DPC** [comment]
bors: try

**Comment by Dylan-DPC** [comment]
bors: r+

**Pull request merged**
