### PR TITLE
Release 0.1.15

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by malbarbo** [comment]
@reitermarkus When the qemu-system supporting was added in https://github.com/rust-embedded/cross/pull/153 and https://github.com/rust-embedded/cross/pull/166 no documentation was provided... It would be great if some documentation could be add before a new release (I can't write it myself now, but maybe someone can).

By the way, thanks for moving the project forward, you are doing a great work!

**Comment by reitermarkus** [comment]
> Actually I'd rather prefer the good old fashioned ASCII quotes...

I think typographic quotes should be preferred for prose.

> I can't write it myself now

I'm not using the `cross run` functionality myself so I can't either. And I don't think this should be blocking a new release, which is long overdue. Would be great if you could do it if you have time in the future.

**Comment by Dylan-DPC** [comment]
> When the qemu-system supporting was added in #153 and #166 no documentation was provided..

@malbarbo Yep sorry about that. The prs were dragging on for too long so didn't want to drag it further

**Comment by therealprof** [comment]
> > Actually I'd rather prefer the good old fashioned ASCII quotes...
 
> I think typographic quotes should be preferred for prose.

These are english text files, often processed on the command line. Typographic quotes are a dime a dozen and will cause random problems for people working with those documents. Until there's a very good reason to deviate I'd rather we stick to plain ASCII.

**Comment by reitermarkus** [comment]
> These are english text files

And that's exactly the reason why we should use quotes appropriate for English text.

This is a Markdown file, there is no good reason why this file would ever be processed by a tool which doesn't support UTF-8 or HTML escape codes.

**Comment by Dylan-DPC** [comment]
Let's not waste time bike-shedding such small things, it's a release note, we can always modify it later

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by therealprof** [comment]
> Let's not waste time bike-shedding such small things, it's a release note, we can always modify it later

No, we cannot. If it's released it will part of the release. Apart from that the point is not to include a change that was not there but to **NOT** make an incorrect change.

**Comment by therealprof** [comment]
@Dylan-DPC Also I'd appreciate if you did not simply dismiss a members concern.

**Pull request merged**
