### PR TITLE
Update musl targets and add new ones

### PR DESCRIPTION
**Pull request by malbarbo**
Use https://github.com/richfelker/musl-cross-make to build the musl toolchain, update base image to Ubuntu 18.04 and add new target. See the individual commits.

### CODE REVIEW

**Comment by malbarbo** [comment]
Thanks to https://github.com/rust-embedded/cross/pull/217, no rust code was changed!

**Comment by malbarbo** [comment]
I think this is the same issue of https://github.com/rust-embedded/cross/pull/171. Very strange. Anyway, the other building is running fine now. I fixed the travis max log issue for this PR, let's see how it goes.

**Comment by Dylan-DPC** [comment]
bors: try

**Comment by Dylan-DPC** [comment]
Somehow trying.tmp has disappeared for this.

**Comment by Dylan-DPC** [comment]
I don't see [the branches section](https://github.com/rust-embedded/cross/blob/master/.travis.yml#L87) after you made changes in the travis configuration

**Comment by malbarbo** [comment]
Oh, I was trying to remove the commit that changed branch sections of .travis.yml, this generated all this confusion... The commit is gone now.

**Comment by malbarbo** [comment]
I think this was interfering with others travis executions.

**Comment by Dylan-DPC** [comment]
bors: try

**Pull request merged**
