### PR TITLE
Upgrade CMake to at least 3.5.1 on all images

### PR DESCRIPTION
**Pull request by Bobo1239**
I'm currently writing Rust bindings for a C project which only supports CMake >= 3.1. I've choosen 3.5.1 as that is the version which is available on Ubuntu 16.04.

### CODE REVIEW

**Comment by japaric** [comment]
That seems reasonable.

Thanks, @Bobo1239.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6a06ed0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6a06ed038b2ea073908386ca4147350ce8652f79 with merge baaa50c16ce11596b3ca3d41425dc003ecc22034...

**Comment by Bobo1239** [comment]
@japaric Can you maybe help me figure out why some builds are failing? I don't really know what I'm looking at...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/317395083?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6a06ed038b2ea073908386ca4147350ce8652f79 with merge 3337313fe613ff011cea54b42da7e3cb172938b4...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/328270884?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6a06ed038b2ea073908386ca4147350ce8652f79 with merge 4af5c0dfc1028b5e236308f2b02905596477516e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/328487779?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6a06ed038b2ea073908386ca4147350ce8652f79 with merge 1c700b8710df825a79a80a890a595ddc5d5a4962...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/332474780?utm_source=github_status&utm_medium=notification)

**Comment by Bobo1239** [comment]
@japaric Upgraded 17.04 to 18.04 and added legacy repositories for 12.04 as these versions are EOL by now. Think it should work now: https://travis-ci.org/Bobo1239/cross/builds/332814064 (excepted that there's a huge MacOS queue...)

**Comment by liuchengxu** [comment]
Any progress on this PR?

**Comment by Bobo1239** [comment]
Currently all PRs are basically blocked until CI gets fixed. Afaik @bgermann has submitted multiple PRs to fix various issues and @malbarbo also has a PR which tries to fix this. Unfortunately neither has been merged as of yet. The last time I actively tried my hands at this I was able to get the number of failing platforms down to one which was failing due to an open rustc issue...

**Comment by Bobo1239** [comment]
Rebased. Should be good to go now.
@liuchengxu The CI-fixing PR (finally) got merged so hopefully this isn't too far off now.

**Comment by Dylan-DPC** [comment]
bors: r+

**Pull request merged**
