### PR TITLE
Update qemu

### PR DESCRIPTION
**Pull request by Luni-4**
Update `qemu` version

Thanks in advance for your review! :)

### CODE REVIEW

**Comment by reitermarkus** [comment]
Seems like there are some new dependencies needed.

**Comment by Luni-4** [comment]
> Seems like there are some new dependencies needed.

Yep, but aren't those dependencies already installed [here](https://github.com/rust-embedded/cross/blob/master/docker/qemu.sh#L37)?

**Comment by Luni-4** [comment]
@reitermarkus 

Do you know how [this](https://dev.azure.com/rust-embedded/cross/_build/results?buildId=603&view=logs&j=e6deedce-f53c-5dcc-524e-14349f140ffd&t=9e60ab89-47e0-5dc9-e657-a2fbb695cbf9&l=3570) error could be solved? I tried to install `selinux` but it's needed to reboot the image.

**Comment by reitermarkus** [comment]
>  Do you know how [this](https://dev.azure.com/rust-embedded/cross/_build/results?buildId=603&view=logs&j=e6deedce-f53c-5dcc-524e-14349f140ffd&t=9e60ab89-47e0-5dc9-e657-a2fbb695cbf9&l=3570) error could be solved?

No idea, sorry.

**Comment by Luni-4** [comment]
Closed in favor of #484

**Pull request closed without merging**
