### PR TITLE
Set up CI with Azure Pipelines.

### PR DESCRIPTION
**Pull request by reitermarkus**
CI on Azure Pipelines is about three times faster than Travis.

### CODE REVIEW

**Comment by reitermarkus** [comment]
An owner needs to approve Azure Pipelines for the org first.

cc @therealprof

**Comment by reitermarkus** [comment]
bors try

**Comment by DiXN** [comment]
Hopefully also with better support for Windows.

**Comment by therealprof** [comment]
@reitermarkus Access is approved.

**Comment by reitermarkus** [comment]
bors try

**Comment by reitermarkus** [comment]
bors retry

**Pull request merged**
