### PR TITLE
upgrade OpenSSL to 1.0.2p

### PR DESCRIPTION
**Pull request by bgermann**

### CODE REVIEW

**Comment by jamesmunns** [comment]
Thanks @bgermann!

@homunkulus r+

**Comment by jamesmunns** [comment]
How about....

bors r+

**Comment by jamesmunns** [comment]
@bgermann it looks like the builds are failing because there is no `1.0.2o` release.

I do not see a release here: https://www.openssl.org/source/, or even here: https://github.com/openssl/openssl/releases

Do you want to roll back your last commit, and we can stick with `1.0.2n`? Let me know if I am missing anything here.

**Comment by jamesmunns** [comment]
See https://travis-ci.org/japaric/cross for more details

**Comment by bgermann** [comment]
It will be released on Tuesday.

**Comment by jamesmunns** [comment]
Okay, we can wait until Tuesday. Feel free to @ me when `1.0.2o` is released, and I can retrigger the CI (and hopefully get this merged).

**Comment by bgermann** [comment]
@jamesmunns new OpenSSL versions are released.

**Comment by jamesmunns** [comment]
@bgermann whats up with the failing `gen-tests`? @japaric is this okay to remove?

**Comment by Bobo1239** [comment]
@bgermann compiler_builtins moved their tests into a separate crate. To do testing you should do the same change as they did: https://github.com/rust-lang-nursery/compiler-builtins/commit/2a134751977538e3c0774ec3e339a50e951863b5#diff-4883bd4f2cfbef38c77abd7eca84ba27R45

**Comment by bgermann** [comment]
Yes, I am also trying to fix the build. #189 is for the FTP issues.

**Comment by bgermann** [comment]
Oh, and wait for cmake-rs to be released, containing https://github.com/alexcrichton/cmake-rs/commit/316dca50e0a4

**Comment by Bobo1239** [comment]
Update: The linking problems are still present :( (https://travis-ci.org/Bobo1239/cross/builds/360497698)

**Comment by bgermann** [comment]
The libgit2/libgit2#4601 fix is in the latest git2-rs release.

**Comment by bgermann** [comment]
Closing this as it contains a fix that also is in #206. I will open a new PR when that PR is merged. Will this be 1.0.2q then...?

**Pull request closed without merging**
