### PR TITLE
macOS host support.

### PR DESCRIPTION
**Pull request by autozimu**

### CODE REVIEW

**Comment by autozimu** [comment]
Ref https://github.com/japaric/cross/issues/102

This simply turn on docker compile on macOS, and depends on the fact that
- x86_65-unknown-linux-gnu toolchain installed
- target std installed

e.g.,
```
rustup toolchain add stable-x86_64-unknown-linux-gnu
rustup target add x86_64-unknown-linux-musl --toolchain stable-x86_64-unknown-linux-gnu
```
enable cross compiling for x86_64-unknown-linux-gnu and x86_64-unknown-linux-musl on a macOS host.

This toolchain and target installation process could be automated within cross, but will require a moderate lines of change.

**Comment by apopiak** [comment]
I'm very much interested in MacOS support. Is this generic or just for `stable-x86_64-unknown-linux-gnu` targets?

**Comment by autozimu** [comment]
Sorry for this delayed response.

It is generic.

What needs to be done here is waiting for opinions of repo owner and after which automatic toolchain installation can be made.

**Comment by Dylan-DPC** [comment]
@autozimu sorry about the silence. Will review it within the next few days

**Comment by Dylan-DPC** [comment]
bors: try

**Comment by robertgzr** [comment]
@autozimu @Dylan-DPC What's the state of this?

**Comment by Dylan-DPC** [comment]
bors: try

**Comment by Dylan-DPC** [comment]
@malbarbo any clue why this is failing?

**Comment by Dylan-DPC** [comment]
bors: try

**Comment by Dylan-DPC** [comment]
bors: try

**Comment by whitfin** [comment]
@Dylan-DPC bors is good, ready to land this?

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by Dylan-DPC** [comment]
bors: r+

**Pull request merged**
