### PR TITLE
temporarily disable broken targets

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by gnzlbg** [comment]
Can someone please add a cron job to run cross CI daily ? 

It takes 2 seconds to add such a cron job to travis, and it would allow us to detect when master breaks cross, as well as to save some headaches to those submitting PRs.

**Comment by jamesmunns** [comment]
@gnzlbg I also added a daily cron job: https://screenshots.firefox.com/W3my389ZfDoiFoWr/travis-ci.org

**Comment by gnzlbg** [comment]
Awesome, thank you @jamesmunns, it would be great if you would get an email on failure, and could open an issue on the repo so that we can try to quickly find which rust PR broke things.

**Comment by jamesmunns** [comment]
@gnzlbg will do. Would you mind opening issues to fix each of the targets that are disabled here?

I'd like to close https://github.com/rust-embedded/cross/issues/228, and instead have one issue per arch that doesn't work.

**Comment by gnzlbg** [comment]
Yeah I'll do that later today and close #228 myself.

**Comment by Dylan-DPC** [comment]
bors: retry

**Comment by gnzlbg** [comment]
So I've also disabled `asmjs`. The emscripten backend of rustc was updated recently (https://github.com/rust-lang/rust/pull/55626), and there have been a couple of related PRs since then, so maybe these broke it (emscripten is using an older LLVM version for asm.js).

**Comment by Dylan-DPC** [comment]
@gnzlbg cool i'll create a tracking issue for that

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by Dylan-DPC** [comment]
I'd prefer to have a release soon so that people can use the tagged version instead of master which will be a lesser burden for us

**Comment by gnzlbg** [comment]
What we need is a cron job every time there is a new nightly. Given that I just had to amend this PR because asmjs broke on nightly, I'd say a daily job is the minimum required. One can configure the cron jobs so that they not run if a job already ran on master on the same day.

**Comment by Dylan-DPC** [comment]
@gnzlbg yes a daily cron is needed but that could mess with existing builds since each build takes roughly 2-3 hours, which means it could block other PRs. We could sort this out by setting a priority (bors makes it easy with `bors: p=..`) but that will mean ensuring we do it for every PR (or at least those that run during the cron) which won't scale well.

**Pull request merged**
